"""migrations

Revision ID: 364608c72903
Revises: 133b6986a876
Create Date: 2022-10-03 00:48:25.654898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364608c72903'
down_revision = '133b6986a876'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
